spring:
    application:
        name: api
    datasource:
        url: jdbc:mysql://localhost:3306/vollmed_api
        username: root
        password: benites1234
        driver-class-name: com.mysql.cj.jdbc.Driver
