spring:
    application:
        name: api
    datasource:
        url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/vollmed_api}
        username: ${DATASOURCE_USERNAME:root}
        password: ${DATASOURCE_PASSWORD:benites1234}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: false
        properties:
            hibernate:
                format_sql: false
