spring:
    application:
        name: api
    datasource:
        url: jdbc:mysql://localhost:3306/vollmed_api
        username: root
        password: benites1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true

server:
    error:
        include-stacktrace: never

api:
    security:
        secret: ${JWT_SECRET:secret}

# spring.data.web.pageable.page-parameter=pagina
# spring.data.web.pageable.size-parameter=tamano
# spring.data.web.sort.sort-parameter=orden
